_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 55
                - 63
                - 71
            "2":
                - 1
                - 41
                - 49
                - 50
                - 55
                - 63
                - 71
            "3":
                - 23
                - 55
                - 61
            "4": 3.11.5
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
find_unused_parameters:
    value: false
gradient_accumulation_steps:
    value: 1
logging_dir:
    value: ./runs/mnist-kacn/train_logs/
mixed_precision:
    value: "no"
model_name:
    value: mnist-kacn
output_dir:
    value: ./runs/mnist-kacn/
wandb:
    value: '{''entity'': ''buka-smart-engines-service'', ''project_name'': ''mnist-kan-convs''}'
