# @package _global_
output_dir: "./runs/cifar10-reskalnet/"
logging_dir: "./runs/cifar10-reskalnet/train_logs/"
model_name: "reskalnet18_32p_cifar10"
gradient_accumulation_steps: 1
mixed_precision: 'no'
epochs: 75
train_batch_size: 96
val_batch_size: 96
dataloader_num_workers: 22
seed: 42

max_train_steps: none

max_grad_norm: 2.

checkpointing_steps: 5000
checkpoints_total_limit: 1000
find_unused_parameters: false

metrics:
  report_type: 'classification'

model:
  groups: 2
  degree: 3
  width_scale: 2
  l2_activation_penalty: 1e-5
  l1_activation_penalty: 1e-6

optim:
  learning_rate: 1e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-4
  adam_epsilon: 1e-8
  lr_warmup_steps: 10
  lr_power: 1
  lr_end: 1e-7
  set_grads_to_none: false

wandb:
  entity: 'add your entity'
  project_name: 'cifar10-kan-convs'

loss:
  label_smoothing: 0.0
